server:
  port: 8082 # order-service 8081 olduğu için bu 8082'de çalışmalı

spring:
  application:
    name: wallet-service

  # Cüzdan Veritabanı Ayarları
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: admin
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Kafka Tüketici (Consumer) ve DTO JSON Ayarları
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: wallet-group-v6
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.flashsale.wallet_service.dto.OrderEvent
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer